### ISSUE TITLE
Customize Backup Schedule

### ISSUE THREAD

**Issue by ghost** [andela-bnkengsa/firebase-backup-bot#1]
Hey @andela-bnkengsa 

Really nice repo here. Thank you!
I was wondering, how can we customise the scheduling of the backup? I want it to run once per day instead for instance.

Cheers,
Piotr

**Comment by andela-bnkengsa** [comment]
Hey @tUrG0n,

For now you'd have to clone the repo and update the cron job in index.coffee. I plan to make it all customizable using yeoman when I get a chance.

**Comment by briceicle** [comment]
Thanks for the suggestion @piotryordanov! checkout the latest release
