### ISSUE TITLE
warning expected help

### ISSUE THREAD

**Issue by rae89** [andela-bnkengsa/firebase-backup-bot#2]
I received the following warning when i run `bin/hubot`

`Hubot> [Thu Nov 03 2016 14:41:52 GMT-0700 (PDT)] WARNING Expected /Users/robert/Documents/firebase-backup-bot/scripts/firebase to assign a function to module.exports, got object`

This is my first time using hubot so I am not sure if I am running it correctly.  I ran `npm install` then I ran `bin/hubot` and received the warning.  Any idea on what I should do?

How would I test the bot to know it is properly running?

**Comment by briceicle** [comment]
@rae89 added some instructions on how to run the bot. I think you are missing the slack token.
